# sample hyprlock.conf
general {
    hide_cursor = false
}

background {
    monitor =
    path = /home/seanyfade/Pictures/MasterSword.jpg
    color = rgba(0, 0, 0, 0)
    blur_passes = 1
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgb(200, 200, 200)
    outer_color = rgba(d4af37ee) rgba(d4af37ee) 45deg
    font_color = rgb(10, 10, 10)
    placeholder_text = Input password...
}

label {
    monitor =
    text = $TIME
    color = rgba(d4af37ee)
    font_size = 100
    position = 0, -80
    halign = center
    valign = center
}
